site_name: Carteira Digital Trânsito

theme:
  name: material
  language: pt
  logo: assets/logos/logo.png
  # favicon:

extra_css:
    - stylesheets/extra.css

repo_url: https://github.com/Requisitos-de-Software/2020.2-CarteiraDigitalTransito

nav:
  - Sobre: index.md
